manifest:
  remotes:
    - name: simpleiot
      url-base: https://github.com/simpleiot
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zephyr-sylvio
      url-base: https://github.com/sylvioalves
    - name: zephyr-iwasz
      url-base: https://github.com/iwasz
    - name: zephyr-cbrake
      url-base: https://github.com/cbrake
  projects:
    - name: zephyr
      remote: zephyr-cbrake
      revision: v4.2.0-cb0
      import:
        name-allowlist:
          - hal_espressif
          - hal_stm32
          - hal_rpi_pico
          - cmsis
          - mbedtls
          - picolibc
    - name: zephyr-snmp
      remote: simpleiot
      revision: main
      path: modules/lib/snmp
    - name: module-sample
      url: https://github.com/yashi/module-sample
      revision: main
      path: modules/lib/sample
    - name: west-debug-tools
      revision: main
      url: https://github.com/hasheddan/west-debug-tools
      west-commands: west-commands.yml
  self:
    path: siot
