/*
Generated by LwipMibCompiler
*/

#ifndef EATON_ATS2_MIB_H
#define EATON_ATS2_MIB_H EATON_ATS2_MIB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib mib_ats2;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* EATON_ATS2_MIB_H */
