/*
Generated by LwipMibCompiler
*/

#ifndef Z_MR_ATS2_MIB_H
#define Z_MR_ATS2_MIB_H Z_MR_ATS2_MIB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib mib_ats2;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* Z_MR_ATS2_MIB_H */
