/*
Generated by LwipMibCompiler
*/

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#include "z-mr.mib.h"
#include "lwip/apps/snmp.h"
#include "lwip/apps/snmp_core.h"
#include "lwip/apps/snmp_scalar.h"
#include "lwip/apps/snmp_table.h"

/* Ask the current mode from snmp.c */
extern s32_t ask_ats_mode(void);

/* The 3 new traps that can be used for ATS_A, ATS_B, and "Unpowered". */
const char *ats2TrapOutputPoweredBySource1_oid = "1.3.6.1.4.1.62530.2.10.15";
const char *ats2TrapOutputPoweredBySource2_oid = "1.3.6.1.4.1.62530.2.10.16";
const char *ats2TrapOutputNotPowered_oid = "1.3.6.1.4.1.62530.2.10.4";

/* --- ats2  ----------------------------------------------------- */
static s16_t ats2measure_scalars_get_value(const struct snmp_scalar_array_node_def *node,
					   void *value);
static const struct snmp_scalar_array_node_def ats2measure_scalars_nodes[] = {
	{4, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* ats2OperationMode */
};
static const struct snmp_scalar_array_node ats2measure_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(
	2, ats2measure_scalars_nodes, ats2measure_scalars_get_value, NULL, NULL);

static const struct snmp_node *const ats2_subnodes[] = {&ats2measure_scalars.node.node};
static const struct snmp_tree_node ats2_root = SNMP_CREATE_TREE_NODE(2, ats2_subnodes);
static const u32_t ats2_base_oid[] = {1, 3, 6, 1, 4, 1, 62530, 2};
const struct snmp_mib mib_ats2 = {ats2_base_oid, LWIP_ARRAYSIZE(ats2_base_oid), &ats2_root.node};

/*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
LWIP MIB generator - preserved section begin
Code below is preserved on regeneration. Remove these comment lines to regenerate code.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*/

/* --- ats2  ----------------------------------------------------- */
static s16_t ats2measure_scalars_get_value(const struct snmp_scalar_array_node_def *node,
					   void *value)
{
	s16_t value_len;
	zephyr_log("ats2measure_scalars_get_value: node %d\n", node->oid);
	switch (node->oid) {
	case 4: {
		/* ats2OperationMode */
		s32_t *v = (s32_t *)value;

		*v = ask_ats_mode();
		zephyr_log("ats2measure_scalars_get_value: returning %d\n", *v);
		value_len = sizeof(s32_t);
		LWIP_UNUSED_ARG(v);
	} break;
	default: {
		LWIP_DEBUGF(
			SNMP_MIB_DEBUG,
			("ats2measure_scalars_get_value(): unknown id: %" S32_F "\n", node->oid));
		value_len = 0;
	} break;
	}
	return value_len;
}

#endif /* LWIP_SNMP */
