/*
Generated by LwipMibCompiler
*/

#ifndef Z_MR_MIB_H
#define Z_MR_MIB_H Z_MR_MIB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib ats2;

/* The 3 new traps that can be used for ATS_A, ATS_B, and "Unpowered". */
extern const char *ats2TrapOutputPoweredBySource1_oid;
extern const char *ats2TrapOutputPoweredBySource2_oid;
extern const char *ats2TrapOutputNotPowered_oid;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* Z_MR_MIB_H */
